springdoc:
  api-docs:
    version: OPENAPI_3_0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cosmic_kitties
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
