changeLogFile=src/main/java/com/myroslav/cosmickitties/db/changelog/db.changelog-master.yaml
url=jdbc:postgresql://localhost:5432/cosmic_kitties
username=postgres
password=postgres
driver=org.postgresql.Driver
